name: go tetsting and building 

on: 
    push:
        branches:  
            - master 

jobs: 

    testing:
        runs-on: ubuntu-latest
        steps:
        - name: print
          run : echo "Hello"
            
    
   
    

