name: Go testing and building 

on: 
    push:
        branches:  
            - master 
    pull_request:
        branches:
            - master

jobs: 

    testing:
        runs-on: ubuntu-latest
        steps:
        - name: clone repo
          uses : actions/checkout@v1
          
        - name: install go
          uses: actions/setup-go@v2
          with:
            go-version: 1.18
            
        - name: test
          run : go test -v ./...
          
    build:
        runs-on: ubuntu-latest
        needs  : testing
        steps:
        - name: clone repo
          uses : actions/checkout@v1
          
        - name: install go
          uses: actions/setup-go@v2
          with:
            go-version: 1.18
            
        - name: test
          run : go build -v ./cmd/example/main.go
      
            
    
   
    

